### PR TITLE
refactored domino ribbon; color legend getting clipped

### PR DESCRIPTION
**Pull request by plotthatstory**

### CODE REVIEW

**Comment by plotthatstory** [comment]
Color legend is getting clipped. Need help fixing it
color_legend_clipped_domino_ribbon
.

**Comment by shreshthmohan** [comment]
The function `{legend} from '../../utils/helpers/colorLegend'` returns a DOM node which itself is an `<svg>` element. I am not sure if the issue of clipping was caused by there being an `svg` element nested inside another `svg` element. That might be the case. But the way this legend function is made, it doesn't currently support trimming the empty space like we do with size legend for instance.

I wasn't seeing the clipping on my laptop before this fix either. But check what you see on your laptop after the fix.

**Comment by shreshthmohan** [comment]
Rest of the review still pending, don't merge yet.

**Comment by shreshthmohan** [comment]
@plotthatstory 
Reviewed, fixed color legend issue and done some minor cleanup. Do check color legend clipping on your laptop before merging.

**Comment by plotthatstory** [comment]
> @plotthatstory Reviewed, fixed color legend issue and done some minor cleanup. Do check color legend clipping on your laptop before merging.

Checked on local. Its working fine. Reviewed changes. Merging with dev.

**Pull request merged**
